version = 0.1

[dev.deploy.parameters]
stack_name = "fhir-sandbox-api-dev"
resolve_s3 = true
s3_prefix = "fhir-sandbox-api-dev"
profile = "bc1-o1-chip-cumulus_f-admin-rl"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" S3Root=\"s3://fhir-sandbox-dev-933137588087/phi_sandbox_cohort_100/\" WafArn=\"arn:aws:wafv2:us-east-1:933137588087:regional/webacl/webacl-internal-access-bch-nat-001/c669ddc0-f599-4b75-a716-25d01e56ea83\""
image_repositories = []

[dev.global.parameters]
region = "us-east-1"
